n11 = input("Digite algo! ")
print('o tipo primitivo desse valor é ', type(n11))
print('\033[4;31m{}\033[m,  É um número?'.format(n11), n11.isnumeric())
print('\033[1;31m{}\033[m, \033[1;31mÉ alfabetico?\033[1;31m, {}{}{}'.format(n11,'\033[4;31m',n11.isalpha(),'\033[m'))
print(n11, "\033[4;34mÉ alfanumérico?\033[m", n11.isalnum())
print(n11, 'Somente possui letras maiusculas?', n11.isupper())
print(n11, 'Somente possui letras minusculas?', n11.islower())
print(n11, 'Está capitalizada -mauscula e minuscula?', n11.istitle())
print(n11, 'pode ser impresso?', n11.isprintable(),)
print(n11, 'É um número decimal?', n11.isdecimal())
print(n11, 'É um valor identificavel?', n11.isidentifier())
print(n11, 'É composto somente de espacos?',  n11.isspace())
#
# 'outra forma de escrever utilizando o .format()'
#
n = input('Digite algo! ')
print('O tipo primitivo do valor "{}" é :'.format(n), type(n))
print('"{}" é um número? '.format(n), n.isnumeric())
print('"{}" é alfabetico? '.format(n), n.isalpha())
print('"{}" é alfanumerico? '.format(n), n.isalnum())
print('"{}" possui somente possui letras maiusculas? '.format(n), n.isupper())
print('"{}" possui somente possui letras minusculas? '.format(n), n.islower())
print('"{}" está capitalizado - possui letras minusculas e minusculas? '.format(n), n.istitle())
print('"{}" pode ser impresso? '.format(n), n.isprintable())
print('"{}" é um numero decimal? '.format(n), n.isdecimal())
print('"{}" pode ser identificado? '.format(n), n.isidentifier())
print('"{}" é composto somente de espacos? '.format(n), n.isspace())
